[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }

library_project = { path = "/Users/marcelaortegaaa/Documents/rust/library_project"}
petgraph = "0.8.3"
rand = "0.9.2"
rasciigraph = "0.3.0"
